# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t achu2002/volttron .

      - name: Push Docker image to Docker Hub
        run: docker push achu2002/volttron:latest
  deploy:
    needs: build
    runs-on: aws-ec2
    
    steps: 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove all Docker images
        run: docker rmi -f $(docker images -q) || true

      - name: Pull image from Docker Hub
        run: docker pull achu2002/volttron:latest

      - name: Stop old container
        run: docker stop volttron-container || true

      - name: Delete old container
        run: docker rm volttron-container || true

      - name: Run new Docker container
        run: docker run -d --env-file /home/ubuntu/comingle/.env -p 5000:5000 --name volttron-container achu2002/volttron:latest

      - name: Restart Nginx
        run: sudo systemctl restart nginx
        

